build: off
environment:
  GOPATH: c:\gopath
stack:
  - go 1.x
test_script:
  - go version
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
after_test:
  - ps: bash <(curl -s https://codecov.io/bash)
