build: off
environment:
  GOPATH: c:\gopath
stack:
  - go 1.x
before_test:
  - choco install codecov
test_script:
  - go version
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
after_test:
  - codecov -f coverage.txt
